app = "sse-api-staging"
primary_region = "iad"

[build]
  dockerfile = "../../infra/docker/api.Dockerfile"

[env]
  NODE_ENV = "staging"
  API_PORT = "3001"
  API_PREFIX = "api/v1"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/ready"

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"
  processes = ["app"]
